/**
 * DocumentCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Document} from "./Document";
export type DocumentCollection = Collection<Document>;
