/**
 * Tag automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Document} from "./Document";
import {User} from "./User";
export interface Tag {
    id?: string
    document?: Document
    user?: User
    version?: string
    changelog?: string
    spec?: any
    insertDate?: string
}
