/**
 * TagCollection automatically generated by SDKgen please do not edit this file manually
 * {@link https://sdkgen.app}
 */

import {Collection} from "./Collection";
import {Tag} from "./Tag";
export type TagCollection = Collection<Tag>;
